spring:

  profiles:
    active: dev

  application:
    name: news
  config:
    import: "optional:configserver:" # default : http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

